### ISSUE TITLE
Radar from israel has wrong iso country code in odimcode

### ISSUE THREAD

**Issue by peterdesmet** [aloftdata/registry#15]
The following radar has been added to the OPERA database:

```
{
        "number": "1397",
        "country": "Israel",
        "countryid": "LLBD40",
        "oldcountryid": "    ",
        "wmocode": "40179",
        "odimcode": "lltlv",
        "location": "Bet Dagan",
        "status": "1",
        "latitude": "32.0070",
        "longitude": "34.8146 ",
        "heightofstation": "",
        "band": " ",
        "doppler": " ",
        "polarization": " ",
        "maxrange": "   ",
        "startyear": "    ",
        "heightantenna": "47",
        "diametrantenna": "4.3",
        "beam": "",
        "gain": "",
        "frequency": "",
        "single_rrr": "",
        "composite_rrr": "",
        "wrwp": ""
    },
```

The ODIM code `lltlv` implies that the country code (first 2 letters) is `ll`, while it is actually `il` (https://www.iso.org/obp/ui/#iso:code:3166:IL). Is this a typo in the OPERA database?

**Comment by peterdesmet** [comment]
Israel should probably also be added to the wiki.

**Comment by peterdesmet** [comment]
Ping @BarVodSur, this is still the case in the DB.

**Comment by peterdesmet** [comment]
This is now corrected: https://aloftdata.eu/radars/#iltlv

**Comment by BarVodSur** [comment]
Dear  Peter,

 

We will check, it's probably a typo.

 

BR, 

Barbara 

 

----------------------------------------------------------------------------------

Barbara Vodarić Šurija, mag.phys & geophys. 

Head of Remote Sensing Department

Meteorological and Hydrological Service of Croatia (DHMZ)

Ravnice 48, 10000 Zagreb, Croatia

mob: +385995356466

e-mail: ***@***.*** ***@***.***> 

www.meteo.hr <http://meteo.hr/> 



 

From: Peter Desmet ***@***.***> 
Sent: Wednesday, November 13, 2024 10:39 AM
To: enram/registry ***@***.***>
Cc: Barbara Vodaric Surija ***@***.***>; Assign ***@***.***>
Subject: [enram/registry] Radar from israel has wrong iso country code in odimcode (#15)

 

The following radar has been added to the OPERA database:

{
        "number": "1397",
        "country": "Israel",
        "countryid": "LLBD40",
        "oldcountryid": "    ",
        "wmocode": "40179",
        "odimcode": "lltlv",
        "location": "Bet Dagan",
        "status": "1",
        "latitude": "32.0070",
        "longitude": "34.8146 ",
        "heightofstation": "",
        "band": " ",
        "doppler": " ",
        "polarization": " ",
        "maxrange": "   ",
        "startyear": "    ",
        "heightantenna": "47",
        "diametrantenna": "4.3",
        "beam": "",
        "gain": "",
        "frequency": "",
        "single_rrr": "",
        "composite_rrr": "",
        "wrwp": ""
    },

The ODIM code lltlv implies that the country code (first 2 letters) is ll, while it is actually il (https://www.iso.org/obp/ui/#iso:code:3166:IL). Is this a typo in the OPERA database?

**Comment by BarVodSur** [comment]
Hello Peter, 
  
Per our latest database update (October 9,2024.), the radar entry for Israel shows ODIM code as 'iltlv', matching the correct ISO country code 'il'. Here is the entry from our database: 
 
 
    { 
        "number": "1397", 
        "country": "Israel", 
        "countryid": "LLBD40", 
        "oldcountryid": "", 
        "wmocode": "40179", 
        "wigosid": "", 
        "odimcode": "iltlv", 
        "location": "Bet Dagan", 
        "status": "1", 
        "latitude": "32.007", 
        "longitude": "34.8146", 
        "heightofstation": "30", 
        "band": "C", 
        "doppler": "Y", 
        "polarization": "S", 
        "maxrange": "280", 
        "startyear": "1996", 
        "heightantenna": "47", 
        "diameterantenna": "4.3", 
        "beam": "1", 
        "gain": "44", 
        "frequency": "5.61", 
        "stratus": "", 
        "cirusnimbus": "", 
        "wrwp": "" 
    } 
    
Best regards, 
Ela 
 
 
 
-- 
Ela Kovačić, mag. phys.- geophys. 
stručna suradnica
DHMZ, Sektor za hidrologiju
Služba za hidrološke studije, analize i prognoze
Odjel za hidrološke prognoze
Ravnice 48, 10000 Zagreb    
  
 
 
 

-----Original Message-----

From: Barbara ***@***.***>
To: 'enram ***@***.***>
Cc: 'Barbara ***@***.***>; Assign ***@***.***>; Ela ***@***.***>
Date: Thursday, 14 November 2024 1:25 PM CET
Subject: RE: [enram/registry] Radar from israel has wrong iso country code in odimcode (#15)

 
 Dear  Peter,   We will check, it's probably a typo.   BR,  Barbara    ---------------------------------------------------------------------------------- Barbara Vodarić Šurija, mag.phys & geophys.  Head of Remote Sensing Department Meteorological and Hydrological Service of Croatia (DHMZ) Ravnice 48, 10000 Zagreb, Croatia mob: +385995356466 e-mail: ***@***.*** www.meteo.hr    
 From: Peter Desmet ***@***.***> 
Sent: Wednesday, November 13, 2024 10:39 AM
To: enram/registry ***@***.***>
Cc: Barbara Vodaric Surija ***@***.***>; Assign ***@***.***>
Subject: [enram/registry] Radar from israel has wrong iso country code in odimcode (#15)    

The following radar has been added to the OPERA database: {         "number": "1397",         "country": "Israel",         "countryid": "LLBD40",         "oldcountryid": "    ",         "wmocode": "40179",         "odimcode": "lltlv",         "location": "Bet Dagan",         "status": "1",         "latitude": "32.0070",         "longitude": "34.8146 ",         "heightofstation": "",         "band": " ",         "doppler": " ",         "polarization": " ",         "maxrange": "   ",         "startyear": "    ",         "heightantenna": "47",         "diametrantenna": "4.3",         "beam": "",         "gain": "",         "frequency": "",         "single_rrr": "",         "composite_rrr": "",         "wrwp": ""     }, 

The ODIM code lltlv implies that the country code (first 2 letters) is ll, while it is actually il (https://www.iso.org/obp/ui/#iso:code:3166:IL). Is this a typo in the OPERA database?
