### ISSUE TITLE
Wrong status for `fiika` and `fikan`

### ISSUE THREAD

**Issue by peterdesmet** [aloftdata/registry#16]
Reported by @nwhpt:

- [fiika](https://aloftdata.eu/radars/#fiika): Ikaalinen not operating anymore
- [fikan](https://aloftdata.eu/radars/#fikan): Kankaanpää is operating

**Comment by peterdesmet** [comment]
@nwhpt note that we are getting data under radar code `fiika`: https://aloftdata.eu/browse/?prefix=baltrad/hdf5/fiika/ but not for `fikan`: https://aloftdata.eu/browse/?prefix=baltrad/hdf5/fikan/

**Comment by nwhpt** [comment]
Ikaalinen was discontinued at some point in spring. There must be an error in the code. I can try to check with IL radar staff. Perhaps they forgot to report it or so.

**Comment by nwhpt** [comment]
Apparently it seems that the Kankaanpää data is currently still delivered as fiika because of some ongoing tests, even though fiika is not working anymore. This should (apparently) change later, once the test phase is over. I don't know when that is.

**Comment by peterdesmet** [comment]
@nwhpt what you report is consistent with what is in the repository: data for `fiika` stopped around [2021-12](https://aloftdata.eu/browse/?prefix=baltrad/hdf5/fiika/2021/12/), data for `fikan` started around [2022-09](https://aloftdata.eu/browse/?prefix=baltrad/hdf5/fikan/2022/09/).

The status for https://aloftdata.eu/radars/#fiika should thus be set to `0` and https://aloftdata.eu/radars/#fikan to `1`, but I notice in the latest update of the radar database by OPERA that fiika was removed and fikan set to 1. For historical purposes, I think it is better if fiika was retained. I will inform Marko Goreta.

**Comment by peterdesmet** [comment]
@nwhpt the reason `fiika` disappeared is because it had moved to a separate `archive` file. The radar list now combines data from both the main and the archive file, so https://aloftdata.eu/radars/#fiika is visible again, with status 0.
